version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    volumes:
      - ./app:/app/app
    restart: unless-stopped 